export const SHOW_MESSAGE    = 'SHOW_MESSAGE'

export const SEND_MESSAGE_FAILED  = "SEND_MESSAGE_FAILED"
export const SEND_MESSAGE_PENDING = "SEND_MESSAGE_PENDING"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_TO_SUCCESS"

export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE"

export const CLEAR_MESSAGES  = "CLEAR_MESSAGES"
export const CHANGE_CHATROOM = "CHANGE_CHATROOM"

export const ADD_CONTACT = "ADD_CONTACT"

export const REQUEST_CONTACTS_FAILED  = "REQUEST_CONTACTS_FAILED" 
export const REQUEST_CONTACTS_PENDING = "REQUEST_CONTACTS_PENDING" 

export const LOGIN_PENDING = "LOGIN_PENDING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED  = "LOGIN_FAILED"

export const KEY_GENERATION_PENDING = "KEY_GENERATION_PENDING";
export const KEY_GENERATION_FAILED  = "KEY_GENERATION_FAILED";
export const KEY_GENERATION_SUCCESS = "KEY_GENERATION_SUCCESS";

export const ENCRYPT_MESSAGE = "ENCRYPT_MESSAGE"
export const DECRYPT_MESSAGE = "DECRYPT_MESSAGE"

export const senders = {OWNER   : "owner", CONTACT : "contact"}